main:
  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/hbstack
    params:
      header: La communité de support de HB
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: GitHub
    parent: support
    url: https://github.com/hbstack
    weight: 1
    params:
      icon:
        vendor: fab
        name: github
      description: le site de hbstack

  - name: Discussions
    parent: support
    url: https://github.com/hbstack/discussions
    weight: 2
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: 提问题和分享你的想法。

  - name: Bugs
    parent: support
    url: https://github.com/hbstack/issues/new
    weight: 3
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Posez les questions
